# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blueprint.root] run return 0
execute on passengers if entity @s[tag=aj.blueprint.data] unless data entity @s {data:{rigHash: '9aeadf23fffd345ca05457f0b4f060f29ce507cd8de3b5540553c5ff9f8d132c'}} on vehicle run function animated_java:blueprint/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1